name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "pending"]
assignees:
  - F0urchette
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: description
    attributes:
      label: Short description
      description: Write a short description of the problem.
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Give us the list of simple steps to follow to reproduce the bug.
      placeholder: |
        - step 1
        - step 2
        - ...
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: Write us what happens after following the steps. Do not hesitate to provide screenshots!
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What is supposed to happen normally, without the bug?
    validations:
      required: true
